// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBPvVfoRiHEXMQZ2YAGDzunDNgA_0no01w',
    appId: '1:603483098467:web:c7c0a65fcb84753c621756',
    messagingSenderId: '603483098467',
    projectId: 'keypocket-61ec3',
    authDomain: 'keypocket-61ec3.firebaseapp.com',
    storageBucket: 'keypocket-61ec3.firebasestorage.app',
    measurementId: 'G-51VHPC5JD3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCLQm1s4SAcehknTBL47doMuvergaIWnc0',
    appId: '1:603483098467:android:688b535a8dcdaee5621756',
    messagingSenderId: '603483098467',
    projectId: 'keypocket-61ec3',
    storageBucket: 'keypocket-61ec3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCv1GGz7-AjZ-25RmsNFM4xzKTYPfu7Obs',
    appId: '1:603483098467:ios:07d9147052e25d32621756',
    messagingSenderId: '603483098467',
    projectId: 'keypocket-61ec3',
    storageBucket: 'keypocket-61ec3.firebasestorage.app',
    iosBundleId: 'com.example.keypocket1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCv1GGz7-AjZ-25RmsNFM4xzKTYPfu7Obs',
    appId: '1:603483098467:ios:07d9147052e25d32621756',
    messagingSenderId: '603483098467',
    projectId: 'keypocket-61ec3',
    storageBucket: 'keypocket-61ec3.firebasestorage.app',
    iosBundleId: 'com.example.keypocket1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBPvVfoRiHEXMQZ2YAGDzunDNgA_0no01w',
    appId: '1:603483098467:web:c7c0a65fcb84753c621756',
    messagingSenderId: '603483098467',
    projectId: 'keypocket-61ec3',
    authDomain: 'keypocket-61ec3.firebaseapp.com',
    storageBucket: 'keypocket-61ec3.firebasestorage.app',
    measurementId: 'G-51VHPC5JD3',
  );
}